# Generated by Django 5.2.7 on 2025-12-28 20:15

import django.contrib.postgres.fields
import django.db.models.deletion
import posts.utils.upload_to
import taggit.managers
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('title_pt_br', models.CharField(max_length=60, null=True, unique=True, verbose_name='título')),
                ('title_en_us', models.CharField(max_length=60, null=True, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('slug_pt_br', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('slug_en_us', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=145, verbose_name='descrição')),
                ('description_pt_br', models.CharField(blank=True, max_length=145, null=True, verbose_name='descrição')),
                ('description_en_us', models.CharField(blank=True, max_length=145, null=True, verbose_name='descrição')),
                ('cover', models.ImageField(blank=True, upload_to=posts.utils.upload_to.post_image_path, verbose_name='capa')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('content_pt_br', tinymce.models.HTMLField(blank=True, null=True, verbose_name='conteúdo')),
                ('content_en_us', tinymce.models.HTMLField(blank=True, null=True, verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='publicado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, verbose_name='é destaque')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='marcadores')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('review', 'Review'), ('opinion', 'Opinião')], max_length=10), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=15, verbose_name='dificuldade')),
                ('source_code', models.URLField(blank=True, verbose_name='código fonte')),
            ],
            options={
                'verbose_name_plural': 'tutoriais',
            },
            bases=('posts.post',),
        ),
    ]
