# Generated by Django 5.2.7 on 2025-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_tutorial_prerequisites'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='posts', to='products.product', verbose_name='produtos'),
        ),
    ]
