# Generated by Django 5.2.7 on 2025-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_categories_post_tags_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=145, verbose_name='descrição'),
        ),
    ]
