# Generated by Django 5.2.7 on 2025-12-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='repository',
            field=models.URLField(blank=True, verbose_name='repositório'),
        ),
    ]
