# Generated by Django 5.2.7 on 2025-12-17 20:44

import django.contrib.postgres.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tutorial_repository'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_opinion',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_review',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='repository',
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('review', 'Review'), ('opinion', 'Opinião')], max_length=10), blank=True, default=list, size=None, verbose_name='gêneros'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='source_code',
            field=models.URLField(blank=True, verbose_name='código fonte'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
