# Generated by Django 5.2.7 on 2025-12-09 17:36

import django.db.models.deletion
import products.utils.upload_to
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('logo', models.FileField(blank=True, null=True, upload_to=products.utils.upload_to.platform_logo_path)),
            ],
            options={
                'verbose_name': 'plataforma',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('image', models.ImageField(upload_to=products.utils.upload_to.product_image_path, verbose_name='imagem')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.category', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.platform', verbose_name='plataforma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products.product', verbose_name='produto')),
            ],
        ),
    ]
